name: core-contracts-release

# Run this workflow manually
# on:
#   workflow_dispatch:
#     inputs:
#       release_version:
#         description: 'Version number of the release to be deployed'
#         required: true
#       network:
#         description: 'Network to deploy core contracts release on'
#         required: true
on: push

env:
  NETWORK: baklava
  VERSION: 4

jobs:
  core_contracts_release:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node 10
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: yarn
        run: yarn

      - name: Build required packages
        # this is a bit grsoss
        run: yarn lerna run build --scope=@celo/base --scope=@celo/utils --@celo/dev-utils --scope=@celo/connect --scope=@celo/wallet-base --scope=@celo/wallet-local

      - name: Verify previous release
        run: yarn --cwd packages/protocol run verify-deployed -b celo-core-contracts-v$(./scripts/github_actions_utils/subtract_one.sh ${{ env.VERSION }}).${{ env.NETWORK }} -n ${{ env.NETWORK }} -f;

      - name: Verify version compatibility
        run: echo "Verify version compatibility"

      - name: Make release
        run: echo "Make release"

      # Runs the CD core contracts release script
      - name: Run the core contract release script
        run: sh ./scripts/github_actions_test.sh celo-core-contracts.v3 alfajores # ${{ github.event.inputs.release_version }} ${{ github.event.inputs.network }}
        shell: bash
